### ISSUE TITLE
sysanalyzer exe is virus

### ISSUE THREAD

**Issue by cuckoo-linux** [dzzie/SysAnalyzer#5]
hi,I downloaded sysanalyzer installer from http://sandsprite.com/iDef/SysAnalyzer/, But when i tried to run it error shows that it cannt be executed as it is a virus:(

**Comment by dzzie** [comment]
thanks I will check to see which AV are having a problem currently. It is hard to make all of them happy they constantly have false positives.

**Comment by dzzie** [comment]
scanning with virustotal only 2/70 are giving this a false positive, webroot and eGambit. What software was alerting you of virus? I will try to contact these two for manual review.
