### ISSUE TITLE
64 bit Is not supported

### ISSUE THREAD

**Issue by kauba** [dzzie/SysAnalyzer#6]
http://sandsprite.com/iDef/SysAnalyzer/ says
"The application supports windows 2000 - windows 10. Including x64 support."
but api_logger gives message:
"can not inject a 32 bit dll into a 64 bit process"
on windows 10

![image](https://user-images.githubusercontent.com/706645/84514390-9f5d7300-acd3-11ea-9bbb-255c0972de9c.png)

**Comment by dzzie** [comment]
Hi, you can try api_log.x64.dll from the repo it is not as well tested as the 32bit version so your milage will vary. The x64 support is primarily for the main sysanalyzer application and even there it is an add on. 

SysAnalyzer was originally developed in the early 2000's on a Win2k system. I am not actively developing it anymore unless I personally need some new feature.
